//! Overlap-aware compaction: the C4 duplicate, at unit scale.
//!
//! `docs/FINDING_rebalance_duplicates_replayed_writes.md` measured 202,000
//! rows where 200,000 were written and 200,000 were distinct. The cause is
//! not in the write path — the primary keys were perfect. It is that
//! duplicate keys collapse only in a compaction's cross-file
//! last-write-wins pass, and a partition holding two or three files never
//! reached the four-file threshold that triggered one. The finding's
//! phrase for how long the duplicate survives is *"potentially forever"*.
//!
//! Catchment's `router-tributary-exactness` reproduces this properly,
//! across a real rebalance. These tests reproduce the *mechanism* in
//! process, in milliseconds, so it stays fixed without needing a cluster.
//!
//! The pair that matters:
//!
//! - `duplicate_rows_in_two_files_are_collapsed` — the fix.
//! - `ascending_flushes_are_not_compacted_below_the_file_threshold` — the
//!   guard on the fix. Without it, "compact whenever ranges touch" would
//!   pass the first test and rewrite every partition forever.

use std::sync::Arc;

use axum::body::Body;
use axum::http::{Request, StatusCode};
use http_body_util::BodyExt;
use tower::ServiceExt;

/// `compact_min_files` is 4 throughout: high enough that two or three
/// files never reach it, which is the condition C4 needs. If a test here
/// passes because the count trigger fired, it is testing nothing.
fn engine(dir: &std::path::Path) -> Arc<timelake_server::Engine> {
    timelake_server::Engine::open(
        dir,
        timelake_server::EngineConfig {
            query_mem_bytes: 256 * 1024 * 1024,
            flush_rows: 1_000_000, // flush only when a test says so
            flush_age_secs: u64::MAX,
            wal_max_bytes: u64::MAX,
            compact_min_files: 4,
            max_concurrent_queries: 4,
            query_timeout_secs: 120,
            gc_grace_secs: 0,
            ..Default::default()
        },
    )
    .unwrap()
}

async fn write_lp(app: &axum::Router, body: &str) -> StatusCode {
    let req = Request::post("/api/v3/write_lp?db=poc").header("content-type", "text/plain");
    app.clone()
        .oneshot(req.body(Body::from(body.to_string())).unwrap())
        .await
        .unwrap()
        .status()
}

async fn count(app: &axum::Router, table: &str) -> i64 {
    let req = Request::post("/api/sql")
        .header("content-type", "application/json")
        .body(Body::from(
            serde_json::json!({"db": "poc", "sql": format!("SELECT COUNT(*) AS n FROM {table}")})
                .to_string(),
        ))
        .unwrap();
    let res = app.clone().oneshot(req).await.unwrap();
    assert!(res.status().is_success(), "count query failed");
    let bytes = res.into_body().collect().await.unwrap().to_bytes();
    let v: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
    v[0]["n"].as_i64().expect("COUNT(*) returned no number")
}

/// One batch of rows, byte-identical every time it is called.
///
/// Identical is the point: Tributary's replay regenerated byte-identical
/// timestamps, so the primary keys of a replayed batch match the original
/// exactly. That is what makes them twins rather than new rows.
fn batch(rows: i64) -> String {
    (0..rows)
        .map(|i| {
            format!(
                "cpu,host=h{} usage=1.0 {}\n",
                i % 10,
                1_700_000_000_000_000_000i64 + i * 1_000_000
            )
        })
        .collect()
}

#[tokio::test]
async fn duplicate_rows_in_two_files_are_collapsed() {
    let dir = tempfile::tempdir().unwrap();
    let eng = engine(dir.path());
    let app = timelake_server::app(Arc::clone(&eng));

    // Two flushes of the SAME rows. Within one flush, last-write-wins
    // already dedups; splitting them across files is what defers the
    // collapse to compaction, and is exactly what a cross-node replay
    // produces.
    assert_eq!(write_lp(&app, &batch(500)).await, StatusCode::NO_CONTENT);
    eng.flush_all().unwrap();
    assert_eq!(write_lp(&app, &batch(500)).await, StatusCode::NO_CONTENT);
    eng.flush_all().unwrap();

    // Two files, `compact_min_files` is 4, so the count trigger cannot
    // fire. Before overlap-aware compaction this is where it stopped, and
    // the querier served both copies indefinitely.
    assert_eq!(
        count(&app, "cpu").await,
        1000,
        "expected the un-compacted duplicate; if this is already 500 the \
         test is not reproducing C4 and proves nothing"
    );

    let compacted = eng.compact_once().unwrap();
    assert_eq!(compacted, 1, "overlap should have made this a candidate");

    assert_eq!(
        count(&app, "cpu").await,
        500,
        "twins survived a compaction they were both in"
    );
}

#[tokio::test]
async fn ascending_flushes_are_not_compacted_below_the_file_threshold() {
    // The guard. A predicate that fired on touching ranges would pass the
    // test above and quietly turn every flush boundary into a rewrite --
    // trading a rare duplicate for permanent write amplification.
    let dir = tempfile::tempdir().unwrap();
    let eng = engine(dir.path());
    let app = timelake_server::app(Arc::clone(&eng));

    let base = 1_700_000_000_000_000_000i64;
    for chunk in 0..3 {
        let body: String = (0..100)
            .map(|i| {
                let ts = base + (chunk * 100 + i) * 1_000_000;
                format!("cpu,host=h{} usage=1.0 {ts}\n", i % 10)
            })
            .collect();
        assert_eq!(write_lp(&app, &body).await, StatusCode::NO_CONTENT);
        eng.flush_all().unwrap();
    }

    assert_eq!(
        eng.compact_once().unwrap(),
        0,
        "three non-overlapping files below the threshold must not compact"
    );
    assert_eq!(count(&app, "cpu").await, 300);
}

#[tokio::test]
async fn a_shared_boundary_timestamp_does_not_trigger_compaction() {
    // A tick-aligned fleet: every host reports at the same instant. A
    // flush landing mid-tick puts that timestamp in both files. Under a
    // non-strict overlap test this compacts on essentially every boundary.
    let dir = tempfile::tempdir().unwrap();
    let eng = engine(dir.path());
    let app = timelake_server::app(Arc::clone(&eng));

    let t0 = 1_700_000_000_000_000_000i64;
    let tick = 10_000_000_000i64;

    // File 1 ends on the tick at t0+tick; file 2 begins on it, with
    // different hosts. Same instant, no shared primary key.
    let first: String = (0..5)
        .map(|i| format!("cpu,host=a{i} usage=1.0 {}\n", t0 + tick))
        .collect();
    let second: String = (0..5)
        .map(|i| format!("cpu,host=b{i} usage=1.0 {}\n", t0 + tick))
        .collect();

    assert_eq!(write_lp(&app, &first).await, StatusCode::NO_CONTENT);
    eng.flush_all().unwrap();
    assert_eq!(write_lp(&app, &second).await, StatusCode::NO_CONTENT);
    eng.flush_all().unwrap();

    assert_eq!(
        eng.compact_once().unwrap(),
        0,
        "files touching at one instant are not duplicates and must not \
         trigger a rewrite"
    );
    assert_eq!(count(&app, "cpu").await, 10, "no row should have been lost");
}

#[tokio::test]
async fn a_late_arrival_is_compacted() {
    // The recover-crash-window tail from FINDING_recover_not_idempotent.md:
    // a file covering a span that has already been written. Not a
    // duplicate by construction, but it is where twins live, and the
    // finding claims overlap-aware compaction closes it too.
    let dir = tempfile::tempdir().unwrap();
    let eng = engine(dir.path());
    let app = timelake_server::app(Arc::clone(&eng));
    let base = 1_700_000_000_000_000_000i64;

    let wide: String = (0..200)
        .map(|i| format!("cpu,host=h{} usage=1.0 {}\n", i % 10, base + i * 1_000_000))
        .collect();
    assert_eq!(write_lp(&app, &wide).await, StatusCode::NO_CONTENT);
    eng.flush_all().unwrap();

    // Arrives after, lands inside the range already covered.
    let late: String = (50..60)
        .map(|i| format!("cpu,host=late usage=2.0 {}\n", base + i * 1_000_000))
        .collect();
    assert_eq!(write_lp(&app, &late).await, StatusCode::NO_CONTENT);
    eng.flush_all().unwrap();

    assert_eq!(
        eng.compact_once().unwrap(),
        1,
        "a late file inside an existing range should compact"
    );
    // 200 originals plus 10 genuinely new series-rows: overlap triggers a
    // merge, it does not delete rows that merely share a timestamp.
    assert_eq!(count(&app, "cpu").await, 210);
}

#[tokio::test]
async fn compaction_is_idempotent_and_does_not_loop() {
    // After a merge the partition holds one file, so nothing overlaps and
    // nothing is over the threshold. If a second pass finds work, the
    // trigger is unstable and the engine would rewrite forever.
    let dir = tempfile::tempdir().unwrap();
    let eng = engine(dir.path());
    let app = timelake_server::app(Arc::clone(&eng));

    assert_eq!(write_lp(&app, &batch(300)).await, StatusCode::NO_CONTENT);
    eng.flush_all().unwrap();
    assert_eq!(write_lp(&app, &batch(300)).await, StatusCode::NO_CONTENT);
    eng.flush_all().unwrap();

    assert_eq!(eng.compact_once().unwrap(), 1);
    assert_eq!(
        eng.compact_once().unwrap(),
        0,
        "a settled partition must not be a candidate again"
    );
    assert_eq!(eng.compact_once().unwrap(), 0);
    assert_eq!(count(&app, "cpu").await, 300);
}

// ---------------------------------------------------------------------
// C2 phase 5: two compactors, one store.
// ---------------------------------------------------------------------

/// Two engines sharing one object store, as two nodes would.
///
/// This is the situation `Role::implemented` currently refuses to create
/// and that #21 will make possible. The fence has to exist first, because
/// the moment a second compactor can run, the old unconditional commit
/// lets both of them land a merge of the same partition.
fn pair_on_one_store(
    dir: &std::path::Path,
) -> (Arc<timelake_server::Engine>, Arc<timelake_server::Engine>) {
    let store = Arc::new(timelake_store::LocalStore::new(&dir.join("shared")).unwrap())
        as Arc<dyn timelake_store::Store>;
    let cfg = || timelake_server::EngineConfig {
        query_mem_bytes: 256 * 1024 * 1024,
        flush_rows: 1_000_000,
        flush_age_secs: u64::MAX,
        wal_max_bytes: u64::MAX,
        compact_min_files: 2,
        max_concurrent_queries: 4,
        query_timeout_secs: 120,
        gc_grace_secs: 0,
        ..Default::default()
    };
    let a =
        timelake_server::Engine::open_with_store(&dir.join("a"), cfg(), Arc::clone(&store), false)
            .unwrap();
    let b =
        timelake_server::Engine::open_with_store(&dir.join("b"), cfg(), Arc::clone(&store), false)
            .unwrap();
    (a, b)
}

#[tokio::test]
async fn two_compactors_cannot_both_land_a_merge_of_one_partition() {
    let dir = tempfile::tempdir().unwrap();
    let (a, b) = pair_on_one_store(dir.path());
    let app_a = timelake_server::app(Arc::clone(&a));

    // Node a ingests and flushes twice: two files, one partition.
    assert_eq!(write_lp(&app_a, &batch(200)).await, StatusCode::NO_CONTENT);
    a.flush_all().unwrap();
    let more: String = (200..400)
        .map(|i| {
            format!(
                "cpu,host=h{} usage=1.0 {}\n",
                i % 10,
                1_700_000_000_000_000_000i64 + i * 1_000_000
            )
        })
        .collect();
    assert_eq!(write_lp(&app_a, &more).await, StatusCode::NO_CONTENT);
    a.flush_all().unwrap();

    // b sees the same store.
    b.catch_up_catalog(a.catalog_head());

    // Both compact. Whichever commits second finds its inputs gone.
    let done_a = a.compact_once().unwrap();
    let done_b = b.compact_once().unwrap();
    assert_eq!(
        done_a + done_b,
        1,
        "exactly one merge may be committed; got a={done_a} b={done_b}"
    );

    // The decisive assertion. Before the fence both merges landed and every
    // row of this partition was stored twice.
    let fresh = timelake_server::Engine::open_with_store(
        &dir.path().join("c"),
        timelake_server::EngineConfig {
            query_mem_bytes: 256 * 1024 * 1024,
            max_concurrent_queries: 4,
            query_timeout_secs: 120,
            ..Default::default()
        },
        Arc::new(timelake_store::LocalStore::new(&dir.path().join("shared")).unwrap())
            as Arc<dyn timelake_store::Store>,
        false,
    )
    .unwrap();
    let app_c = timelake_server::app(fresh);
    assert_eq!(
        count(&app_c, "cpu").await,
        400,
        "a second merge landed: the partition holds every row twice"
    );
}

#[tokio::test]
async fn a_losing_compactor_reports_no_compaction_and_no_error() {
    // Losing a race is ordinary once more than one node compacts. It must
    // not surface as an error, and it must not be counted as a compaction
    // -- a metric that climbed here would make normal concurrency look
    // like a fault to whoever is watching the dashboard.
    let dir = tempfile::tempdir().unwrap();
    let (a, b) = pair_on_one_store(dir.path());
    let app_a = timelake_server::app(Arc::clone(&a));

    assert_eq!(write_lp(&app_a, &batch(200)).await, StatusCode::NO_CONTENT);
    a.flush_all().unwrap();
    assert_eq!(write_lp(&app_a, &batch(200)).await, StatusCode::NO_CONTENT);
    a.flush_all().unwrap();
    b.catch_up_catalog(a.catalog_head());

    assert_eq!(a.compact_once().unwrap(), 1);
    let loser = b.compact_once();
    assert!(loser.is_ok(), "a lost race is not an error: {loser:?}");
    assert_eq!(loser.unwrap(), 0, "a stale merge is not a compaction");
    assert!(
        b.metrics_text_impl()
            .contains("timelake_stale_merges_total 1"),
        "the discarded merge should be visible, so wasted work can be measured"
    );
}
