[package]
name = "timelake-query"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
datafusion.workspace = true
serde_json.workspace = true
tokio.workspace = true
async-trait = "0.1"
tracing.workspace = true
bytes.workspace = true
timelake-store = { path = "../store" }
timelake-catalog = { path = "../catalog" }

[dev-dependencies]
timelake-buffer = { path = "../buffer" }
timelake-ingest = { path = "../ingest" }

