[agent]
  interval = "2s"
  flush_interval = "2s"
[[inputs.cpu]]
[[outputs.influxdb_v2]]
  urls = ["http://tldb-http-probe:8086"]
  token = "s3cr3t-telegraf-v2"
  organization = "acme"
  bucket = "poc"
[[outputs.influxdb]]
  urls = ["http://tldb-http-probe:8086"]
  database = "poc"
  username = "tl-telegraf"
  password = "s3cr3t-telegraf-v1"
