[package]
name = "timelake-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
flate2.workspace = true
timelake-auth = { path = "../auth" }
timelake-audit = { path = "../audit" }
timelake-config = { path = "../config" }
timelake-ingest = { path = "../ingest" }
timelake-prometheus = { path = "../prometheus" }
