[package]
name = "timelord-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
axum.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
timelord-api = { path = "../api" }
timelord-ingest = { path = "../ingest" }
timelord-wal = { path = "../wal" }
timelord-buffer = { path = "../buffer" }
timelord-query = { path = "../query" }
timelord-store = { path = "../store" }
timelord-catalog = { path = "../catalog" }
timelord-compact = { path = "../compact" }
timelord-flight = { path = "../flight" }
timelord-tls = { path = "../tls" }
axum-server.workspace = true

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
tempfile.workspace = true
flate2.workspace = true



